export const models= [
    {
        id:1,
        name:"T-X",
        serialNumber:56789954
    },
    {
        id:2,
        name:"RRR-X",
        serialNumber:7644
    },
    {
        id:3,
        name:"TRRR-X",
        serialNumber:76543
    },
    {
        id:4,
        name:"TQQQ-X",
        serialNumber:210344
    },
    {
        id:5,
        name:"TKKKK-X",
        serialNumber:3421
    },
    {
        id:6,
        name:"TPPP-X",
        serialNumber:987655
    },
    {
        id:7,
        name:"FFFT-X",
        serialNumber:56789954
    },
    {
        id:8,
        name:"TÉÉÉÉ-X",
        serialNumber:67832
    },
    {
        id:9,
        name:"T-X",
        serialNumber:32105
    },
    {
        id:10,
        name:"ZZZZZT-X",
        serialNumber:5678956789954
    },
    {
        id:11,
        name:"MMMMT-X",
        serialNumber:22222
    }
]